//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Occupational_Safety_and_Health
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersView
    {
        public int TabNomer { get; set; }
        public int Otd { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<bool> WriteMO { get; set; }
        public Nullable<bool> WriteOT { get; set; }
        public Nullable<bool> WriteSIZ { get; set; }
        public Nullable<bool> CreateUsers { get; set; }
    }
}
