//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Occupational_Safety_and_Health.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReadySIZ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReadySIZ()
        {
            this.ReadyTemplates = new HashSet<ReadyTemplate>();
            this.UsersSIZs = new HashSet<UsersSIZ>();
        }
    
        public int Id { get; set; }
        public int SIZNameId { get; set; }
        public int TypeDeffSIZId { get; set; }
        public int CompositionSIZId { get; set; }
        public int TermUseSIZId { get; set; }
        public int PeridYearId { get; set; }
    
        public virtual CompositionSIZ CompositionSIZ { get; set; }
        public virtual PeriodYear PeriodYear { get; set; }
        public virtual SIZName SIZName { get; set; }
        public virtual TermUseSIZ TermUseSIZ { get; set; }
        public virtual TypesDeffSIZ TypesDeffSIZ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReadyTemplate> ReadyTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersSIZ> UsersSIZs { get; set; }
    }
}
