//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Occupational_Safety_and_Health.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReadyTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReadyTemplate()
        {
            this.UsersTemplates = new HashSet<UsersTemplate>();
            this.UserTemplateHistories = new HashSet<UserTemplateHistory>();
        }
    
        public int Id { get; set; }
        public int NameTemplateId { get; set; }
        public int ReadySIZId { get; set; }
    
        public virtual NameTemplate NameTemplate { get; set; }
        public virtual ReadySIZ ReadySIZ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersTemplate> UsersTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserTemplateHistory> UserTemplateHistories { get; set; }
    }
}
