//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Occupational_Safety_and_Health.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisteredPC
    {
        public int Id { get; set; }
        public string UUID { get; set; }
        public int KSP { get; set; }
        public bool Active { get; set; }
    
        public virtual T2Otdel T2Otdel { get; set; }
    }
}
