//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Occupational_Safety_and_Health.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersViolation
    {
        public int Id { get; set; }
        public int TabNomer { get; set; }
        public int TypeViolationsId { get; set; }
        public int BonusPunishmentId { get; set; }
        public int AdministrativePunishmentId { get; set; }
        public System.DateTime Date { get; set; }
        public bool Active { get; set; }
    
        public virtual AdministrativePunishment AdministrativePunishment { get; set; }
        public virtual BonusPunishment BonusPunishment { get; set; }
        public virtual T2Vvod T2Vvod { get; set; }
        public virtual TypesViolation TypesViolation { get; set; }
    }
}
